AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  awsOTAManagedPolicyName:
    Type: String
    Default: "arn:aws:iam::aws:policy/service-role/AmazonFreeRTOSOTAUpdate"
    Description: awsOTAManagedPolicy

Resources: 
  OTAServiceRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "iot.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: 
          - !Ref awsOTAManagedPolicyName
      Path: "/"
      RoleName: OTAServiceRole
      
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "OTAServiceRoleInlinePolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "iam:GetRole"
              - "iam:PassRole"
            Resource: 
              - !Join ['', ['arn:aws:iam::', Ref: 'AWS::AccountId',':role/', Ref: 'OTAServiceRole']]
          - 
            Effect: "Allow"
            Action: 
               - 's3:GetObjectVersion'
               - 's3:GetObject'
               - 's3:PutObject'
            Resource: 'arn:aws:s3:::afr-ota*'
      Roles: 
        - 
          Ref: OTAServiceRole